// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbuficnurormltrlcpxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhidWZpY251cm9ybWx0cmxjcHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MTQ5MTcsImV4cCI6MjA3ODE5MDkxN30.tw7GMzNONdTrp9sO1tb7t0syAp024lMsYJEtUYl5QBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});